name: Fetch Daily Card

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:  # Allows manual runs from GitHub Actions UI

jobs:
  fetch_card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python app/daily_fetch.py

      - name: Push changes using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://$GH_PAT@github.com/timothy-liew/mtg_white_etl.git

          git fetch origin master 
          git checkout master || git checkout -b master

          # Force-pull the latest changes before pushing
          git pull origin master --rebase --strategy=ours

          git add app/data/cards.db || echo "No changes to commit"
          git commit -m "Update daily card" || echo "No changes to commit"
          git push origin master || echo "Nothing to push"


